server:
  port: 9999


spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: db01
      #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        db01:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/st-df?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          driver-class-name: com.mysql.cj.jdbc.Driver
        db02:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/sttest5?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          driver-class-name: com.mysql.cj.jdbc.Driver


##mybatis日志
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml,classpath:/other/*.xml
  global-config:
    db-config:
      #驼峰下划线转换
      table-underline: true
      db-column-underline: true
  configuration:
    ##配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as(没开启这个，sql需要写as:select user_id as userId)
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



  #redis 配置
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 100   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 100     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: '123456'
    port: 6379
